### ISSUE TITLE
MAC Gui version of Loki wallet cannot connect to daemon

### ISSUE THREAD

**Issue by ivylingheechin** [loki-project/loki-gui#12]
I tried 5 Times n still cannot connect to daemon. Pls help.

**Comment by sumitnagariya** [comment]
+1

ERROR	msgwriter	src/common/scoped_message_writer.h:102	Error: Couldn't connect to daemon: 127.0.0.1:22023
2018-05-10 18:40:14.300	  0x7fff7be7e300	INFO 	logging	contrib/epee/src/mlog.cpp:185	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO

**Comment by maximka1** [comment]
Solution. Apparently users using OSx earlier than 10.13 are experiencing issues with connection to daemon. I ran lokid manually and I see that the issue is with _clock_gettime, to which your library is referring to and which is absent in earlier OSx. The current workaround seems to be to ignore _POSIX_TIMERS. You can refer to this thread pocoproject/poco#1453 which had similar issue solved. Check for backwards compatibility after.

**Comment by maximka1** [comment]
Copied for Lokid:
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /loki-wallet-gui.app/Contents/MacOS/lokid (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /loki-wallet-gui.app/Contents/MacOS/lokid (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by ivylingheechin** [comment]
I dun understand . My is version 10.11.6 so it’s old version n that why cannot work? Then what must I do??? Upgrade the OS? U mean new MAC will surely work?

**Comment by maximka1** [comment]
@ivylingheechin Yes, it doesn't work because you're on older version of Mac. You should wait for the Loki team to respond and hopefully fix this issue.

Alternatively, you can upgrade to new OSx. I personally don't like to advise upgrade, because of some issues with the new OS I don't want to talk about. So I'm personally staying on 10.11 and waiting for the Loki team to fix the code.

**Comment by Doy-lee** [comment]
Yes this has been brought to the teams attention and we're currently setting up some older machines and rebuilding. Thanks maximka1 and sot in Discord for the technical information, we will update shortly.

**Comment by Doy-lee** [comment]
Hi, please try the builds available here:

Gui: loki-gui-mac64-v0.1.0.zip: https://loki.network/wp-content/uploads/2018/05/loki-gui-mac64-v0.1.0.zip
Gui SHA256: 314fb5d121377d0ea5425fe57956b090208e1780e7a1015737e9a33140e06bb3
Daemon: lokid-mac64-v0.1.0zip: https://loki.network/wp-content/uploads/2018/05/lokid-mac64-v0.1.0.zip
Daemon SHA256: c08ad86189d6a6865199168d89db97f9a161699881dd2dfb5697905597279d11

If the results are positive, these will be replacing the release links.

**Comment by maximka1** [comment]
@Doy-lee 

Downloaded the gui build you shared, works fine on my machine (10.11.16). Thank you!

**Comment by ivylingheechin** [comment]
i click the first link or th second one? what is the difference?

**Comment by Doy-lee** [comment]
You are probably interested in the GUI, which is the standard type of mac application. The daemon is just for terminal use.
