### ISSUE TITLE
GUI MAC Wallet daemon failed

### ISSUE THREAD

**Issue by samisilva** [loki-project/loki-gui#14]
error message for daemon

**Comment by samisilva** [comment]
Mac Loki GUI wallet unable to connect to daemon.

Error message

"Daemon failed to start
Please check your wallet and daemon log for errors. You can also try to start lokid manually."

**Comment by maximka1** [comment]
Apparently users using OSx earlier than 10.13 are experiencing issues with connection to daemon. I ran lokid manually and I see that the issue is with _clock_gettime, to which your library is referring to and which is absent in earlier OSx. The current workaround seems to be to ignore _POSIX_TIMERS. You can refer to this thread https://github.com/pocoproject/poco/issues/1453 which had similar issue solved. Check for backwards compatibility after.

**Comment by Doy-lee** [comment]
Please try the builds available in issue #12
